### ISSUE TITLE
AttributeError: 'bow_minibatcher' object has no attribute 'mega_batcher'

### ISSUE THREAD

**Issue by wangshaonan** [mingdachen/disentangle-semantics-syntax#2]
When running the code with default parameters, there is an error in the very beginning of the second epoch as follows:

Traceback (most recent call last):
  File "train.py", line 225, in <module>
    run(e)
  File "train.py", line 80, in run
    enumerate(train_batch):
  File "/home/snwang/project/sentence_semantic_syntax/disentangle-semantics-syntax-master/data_utils.py", line 620, in __next__
    return self._pad(data1, data2) + [idx]
  File "/home/snwang/project/sentence_semantic_syntax/disentangle-semantics-syntax-master/data_utils.py", line 588, in _pad
    self.mega_batcher.get_batch()
AttributeError: 'bow_minibatcher' object has no attribute 'mega_batcher'
()

This is probably because in the second epoch, self.maga_batch = 20 > 1, and the mega_batcher function is called in _pad(). But the mega_batcher function is only defined in _reset() which is not carried out in the first run because of self.maga_batch = 0.

**Comment by mingdachen** [comment]
Hi, thanks for the detailed report! I've pushed a fix. Let me know if there are other problems.
